set_property SRC_FILE_INFO {cfile:{C:/Users/Dennis Wong/Documents/FPGA_Projects/I2C_Controller/I2C_Master/I2C_Master.srcs/constrs_1/new/my_crs.xdc} rfile:../../../I2C_Master.srcs/constrs_1/new/my_crs.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports system_clock]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports reset_n]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports I2C_SDA]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A16 [get_ports I2C_SCLK]
